"""
/**
 * **Problem 2 - Even Fibonacci Numbers**
 *
 * Each new term in the Fibonacci sequence is generated by adding the previous two terms.
 * By starting with 1 and 2, the first 10 terms will be:
 *
 * 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
 *
 * ---
 * By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
 *
 */
"""
from utils import fibonacci

def problem2() -> int:
  def main() -> int:
    LIMIT = 4000000
    fibList = fibonacci.returnFibonacciNumbersUntil(LIMIT)
    fibListEven = []

    for num in fibList:
      if (num % 2 == 0):
        fibListEven.append(num)
    
    return sum(fibListEven)

  result = main()
  return result

print(f'problem 2 answer = {problem2()}')